# Generated by Django 6.0.2 on 2026-02-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = []
